services:
    netgen_remote_media.controller.folder.load:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\Folder\Load
        public: true
        arguments:
            - '@netgen_remote_media.provider'

    netgen_remote_media.controller.folder.create:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\Folder\Create
        public: true
        arguments:
            - '@netgen_remote_media.provider'

    netgen_remote_media.controller.browse:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\Browse
        public: true
        arguments:
            - '@netgen_remote_media.provider'

    netgen_remote_media.controller.callback.cloudinary.notify:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\Callback\Cloudinary\Notify
        public: true
        arguments:
            - '@netgen_remote_media.provider.cloudinary.gateway.cached'
            - '@netgen_remote_media.provider'
            - '@netgen_remote_media.provider.cloudinary.verifier.controller.signature'
            - '@doctrine.orm.entity_manager'
