services:
    netgen_remote_media.controller.facets.load:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\Facets\Load
        public: true
        arguments:
            - '@netgen_remote_media.provider'
            - '@translator'

    netgen_remote_media.controller.folder.load:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\Folder\Load
        public: true
        arguments:
            - '@netgen_remote_media.provider'

    netgen_remote_media.controller.folder.create:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\Folder\Create
        public: true
        arguments:
            - '@netgen_remote_media.provider'

    netgen_remote_media.controller.resource.browse:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\Resource\Browse
        public: true
        arguments:
            - '@netgen_remote_media.provider'

    netgen_remote_media.controller.resource.upload:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\Resource\Upload
        public: true
        arguments:
            - '@netgen_remote_media.provider'
            - '@netgen_remote_media.factory.md5_file_hash'
            - '@translator'

    netgen_remote_media.controller.resource.view:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\Resource\View
        public: true
        arguments:
            - '@netgen_remote_media.provider'
        calls:
            - [setContainer, ['@service_container']]

    netgen_remote_media.controller.location.create:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\Location\Create
        public: true
        arguments:
            - '@netgen_remote_media.provider'
            - '@netgen_remote_media.service.remote_resource_service'
        calls:
            - [setContainer, ['@service_container']]

    netgen_remote_media.controller.location.delete:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\Location\Delete
        public: true
        arguments:
            - '@netgen_remote_media.provider'
        calls:
            - [setContainer, ['@service_container']]

    netgen_remote_media.controller.location.update:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\Location\Update
        public: true
        arguments:
            - '@netgen_remote_media.provider'
            - '@netgen_remote_media.service.remote_resource_service'
        calls:
            - [setContainer, ['@service_container']]

    netgen_remote_media.controller.location.selected_image:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\Location\SelectedImage
        public: true
        arguments:
            - '@netgen_remote_media.provider'
            - '@netgen_remote_media.service.remote_resource_service'
        calls:
            - [setContainer, ['@service_container']]

    netgen_remote_media.controller.callback.cloudinary.notify:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\Callback\Cloudinary\Notify
        public: true
        arguments:
            - '@netgen_remote_media.provider.cloudinary.gateway.cached'
            - '@netgen_remote_media.provider'
            - '@netgen_remote_media.provider.cloudinary.verifier.controller.signature'
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
        calls:
            - [setContainer, ['@service_container']]

    netgen_remote_media.controller.configuration:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\Configuration
        public: true
        arguments:
            - '@router'
            - '@translator'
            - '@netgen_remote_media.resolver.variation'
        calls:
            - [setContainer, ['@service_container']]
