services:
    netgen_remote_media.handler_registry:
        class: Netgen\RemoteMedia\Core\Transformation\Registry

    netgen_remote_media.resolver.variation:
        class: Netgen\RemoteMedia\Core\Resolver\Variation
        lazy: true
        calls:
            - [setVariations, ["%netgen_remote_media.image_variations%"]]
            - [setServices, ["@netgen_remote_media.handler_registry", "@?logger"]]

    netgen_remote_media.provider.cloudinary.gateway:
        class: Netgen\RemoteMedia\Core\Provider\Cloudinary\Gateway\CloudinaryApiGateway
        arguments:
            - '@netgen_remote_media.provider.cloudinary.factory.remote_resource'
            - '@netgen_remote_media.provider.cloudinary.factory.search_result'
            - '@netgen_remote_media.provider.cloudinary.resolver.search_expression'
        calls:
            - [initCloudinary, ['%netgen_remote_media.parameters.cloudinary.account_name%', '%netgen_remote_media.parameters.cloudinary.account_key%', "%netgen_remote_media.parameters.cloudinary.account_secret%", "%netgen_remote_media.parameters.use_subdomains%"]]

    netgen_remote_media.provider.cloudinary.gateway.cached:
      class: Netgen\RemoteMedia\Core\Provider\Cloudinary\Gateway\Cache\Psr6CachedGateway
      arguments:
        - "@netgen_remote_media.provider.cloudinary.gateway"
        - "@netgen_remote_media.cache.pool"
        - "%netgen_remote_media.cache.ttl%"

    netgen_remote_media.provider.cloudinary:
        class: Netgen\RemoteMedia\Core\Provider\Cloudinary\CloudinaryProvider
        arguments:
            - "@netgen_remote_media.handler_registry"
            - "@netgen_remote_media.resolver.variation"
            - "@doctrine.orm.entity_manager"
            - "@netgen_remote_media.provider.cloudinary.gateway.cached"
            - "@netgen_remote_media.factory.date_time"
            - "@netgen_remote_media.provider.cloudinary.resolver.upload_options"
            - "@?logger"

    netgen_remote_media.helper:
        class: Netgen\RemoteMedia\Core\Helper
        arguments:
            - "@netgen_remote_media.provider"

    netgen_remote_media.provider.cloudinary.converter.resource_type:
        class: Netgen\RemoteMedia\Core\Provider\Cloudinary\Converter\ResourceType
        public: false

    netgen_remote_media.provider.cloudinary.factory.remote_resource:
        class: Netgen\RemoteMedia\Core\Provider\Cloudinary\Factory\RemoteResource
        public: false
        arguments:
            - '@netgen_remote_media.provider.cloudinary.converter.resource_type'

    netgen_remote_media.provider.cloudinary.factory.search_result:
        class: Netgen\RemoteMedia\Core\Provider\Cloudinary\Factory\SearchResult
        public: false
        arguments:
            - '@netgen_remote_media.provider.cloudinary.factory.remote_resource'

    netgen_remote_media.provider.cloudinary.resolver.upload_options:
        class: Netgen\RemoteMedia\Core\Provider\Cloudinary\Resolver\UploadOptions
        public: false

    netgen_remote_media.provider.cloudinary.resolver.search_expression:
        class: Netgen\RemoteMedia\Core\Provider\Cloudinary\Resolver\SearchExpression
        public: false
        arguments:
            - '@netgen_remote_media.provider.cloudinary.converter.resource_type'

    netgen_remote_media.factory.date_time:
        class: Netgen\RemoteMedia\Core\Factory\DateTime

    netgen_remote_media.provider.cloudinary.verifier.controller.signature:
        class: Netgen\RemoteMedia\Core\Provider\Cloudinary\Verifier\Request\Signature
        public: false
