services:
    netgen_remote_media.form.data_transformer.remote_media:
        class: Netgen\RemoteMedia\Form\DataTransformer\RemoteMediaTransformer
        arguments:
            - "@netgen_remote_media.provider"
                
    netgen_remote_media.form.type.remote_media:
        class: Netgen\RemoteMedia\Form\Type\RemoteMediaType
        arguments:
            - "@netgen_remote_media.form.data_transformer.remote_media"
            - "@netgen_remote_media.provider"
        tags:
            - { name: form.type }
