orm:
    entity_managers:
        default:
            mappings:
                NetgenRemoteMediaBundle:
                    type: xml
                    prefix: Netgen\RemoteMedia\API\Values
                    dir: "%kernel.project_dir%/vendor/netgen/remote-media-bundle/bundle/Resources/config/doctrine"
                    is_bundle: false
