netgen_remote_media_callback_cloudinary_notify:
    path: /ngremotemedia/callback/cloudinary/notify
    defaults:
        _controller: netgen_remote_media.controller.callback.cloudinary.notify
    methods: [POST]
