name: Coding standards

on:
  push:
    branches:
      - '3.[0-9]+'
  pull_request: ~

jobs:
  php-cs-fixer:
    name: PHP CS Fixer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: OskarStark/php-cs-fixer-ga@master
        with:
          args: --diff --dry-run
