name: Tests

on:
  push:
    branches:
      - 'master'
  pull_request: ~

jobs:
  tests:
    name: ${{ matrix.php }} / ${{ matrix.symfony }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['7.2', '7.3', '7.4']
        symfony: ['~3.4.0']
        deps: ['normal']
        include:
          - php: '7.2'
            symfony: '~3.4.0'
            deps: 'low'

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - run: composer --version
      - run: composer validate --strict

      # Install Flex as a global dependency to enable usage of extra.symfony.require
      # while keeping Flex recipes from applying
      - run: composer global config --no-plugins allow-plugins.symfony/flex true
      - run: composer global require --no-scripts symfony/flex

      # Install eZ Publish legacy installer as a global dependency
      - run: composer config --no-plugins allow-plugins.ezsystems/ezpublish-legacy-installer true

      - run: composer config extra.symfony.require ${{ matrix.symfony }}

      -
        run: composer update --prefer-dist
        if: ${{ matrix.deps != 'low' }}

      -
        run: composer update --prefer-dist --prefer-lowest --prefer-stable
        if: ${{ matrix.deps == 'low' }}

      - run: vendor/bin/phpunit -c phpunit.xml --colors=always
